name: YAML with Telus Org

on:
  workflow_dispatch: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
        
jobs:
  buildandtest:

    runs-on:  [self-hosted, telus-org-runner]
    #runs-on: ubuntu-latest
    
    env:
        GH_READ_PACKAGES_TOKEN: ${{ secrets.GH_READ_PACKAGES_TOKEN }}
        TESTING_USER: ${{ secrets.TESTING_USER }} 
        GH_CD_RT: ${{ secrets.GH_CD_RT }}
        GH_CS_RT: ${{ secrets.GH_CS_RT }}
        GH_RT: ${{ secrets.GH_RT }}
    


    steps:
    - uses: actions/checkout@v3      
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
       maven-version: 3.8.2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: temurin
        
   
   # - name: Build with Maven
      #run: mvn --settings ./settings.xml -B package --file pom.xml   
    #- name: install dependencies
     # run: mvn -B install --no-transfer-progress --quiet
     
    - name: install browser libraries
      run: |
         sudo add-apt-repository main
         sudo add-apt-repository universe
         sudo add-apt-repository restricted
         sudo add-apt-repository multiverse
         sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
         sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
         sudo apt-get update
         sudo apt-get install -y google-chrome-stable
         sudo apt-get install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libnss3 lsb-release xdg-utils wget ca-certificates

     
     
    - name: Run tests        
      #run: mvn --settings ./settings.xml -B test -DexecutionType=RORGP -Dwebdriver.chrome.driver=/home/batch_vm/actions-runner-2/chromedriver -Dexecution.environment=ITN02 -DNCID=333003 -DUserName=x249799 -DPassword=MY_SECRET1${{ env.MY_SECRET1 }}
      #run: mvn --settings ./settings.xml -B -Dmaven.test.failure.ignore=false -Dselenium.browser.options=P_HEADLESS_ALONE -DexecutionType=RORGP -Dexecution.environment=ITN02 -DNCID=333003 -DUserName=x249799 -DPassword=${{ env.MY_SECRET1 }} package --file pom.xml test
      run: mvn --settings ./settings.xml -B package --file pom.xml test

    - name: Attach Report
      uses: actions/upload-artifact@v2
      with:
        name: extent-reports.zip
        path: "target/extent-reports.zip"
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
   # - name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
